[package]
name = "ekkles"
version = "0.1.0"
edition = "2024"

[dependencies]
# GUI Framework
iced = {version = "0.13.1", default-features = false, features = ["wgpu", "tokio"]}
# Pro logování událostí v programu
log = {version = "0.4.27"}
pretty_env_logger = {version = "0.5.0"}
# Jednoduchý error handling
anyhow = "1.0.98"
# Pro (pouze) čtení XML souborů
roxmltree = { version = "0.20.0", default-features = false, features = ["std"] }
# Manipulace s databází (zabudovaná sqlite)
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "sqlite", "macros"] }
# Pro jednorázovou inicializaci regexů
lazy_static = "1.5.0"
# Pro parsování slov z XML dokumentů písní
regex = "1.11.1"

[dev-dependencies]
# Na tokiu už jsem závislý skrze iced a a sqlx, ale abych měl přístup ke věcem z tokia
# (např. anotace pro testy async funkcí), natáhnu si to i přímo ve stejné verzi.
tokio = {version = "1.44.2", features = ["test-util"]}
# Aby v testech byly přehledné barevné diffy
pretty_assertions = "1.4.1"
