use anyhow::{Context, Result, anyhow, bail};
use log::trace;
use sqlx::{Sqlite, pool::PoolConnection, query};
use std::{fmt::Display, ops::RangeInclusive, str::FromStr};

use super::NUM_BOOKS_IN_THE_BIBLE;

/// Seznam všech knih v Bibli
pub const BIBLE_BOOKS: [Book; NUM_BOOKS_IN_THE_BIBLE] = [
    Book::Genesis,
    Book::Exodus,
    Book::Leviticus,
    Book::Numbers,
    Book::Deuteronomy,
    Book::Joshua,
    Book::Judges,
    Book::Ruth,
    Book::Samuel1,
    Book::Samuel2,
    Book::Kings1,
    Book::Kings2,
    Book::Chronicles1,
    Book::Chronicles2,
    Book::Ezra,
    Book::Nehemiah,
    Book::Esther,
    Book::Job,
    Book::Psalms,
    Book::Proverbs,
    Book::Ecclesiastes,
    Book::SongOfSolomon,
    Book::Isaiah,
    Book::Jeremiah,
    Book::Lamentations,
    Book::Ezekiel,
    Book::Daniel,
    Book::Hosea,
    Book::Joel,
    Book::Amos,
    Book::Obadiah,
    Book::Jonah,
    Book::Micah,
    Book::Nahum,
    Book::Habakkuk,
    Book::Zephaniah,
    Book::Haggai,
    Book::Zechariah,
    Book::Malachi,
    Book::Matthew,
    Book::Mark,
    Book::Luke,
    Book::John,
    Book::Acts,
    Book::Romans,
    Book::Corinthians1,
    Book::Corinthians2,
    Book::Galatians,
    Book::Ephesians,
    Book::Philippians,
    Book::Colossians,
    Book::Thessalonians1,
    Book::Thessalonians2,
    Book::Timothy1,
    Book::Timothy2,
    Book::Titus,
    Book::Philemon,
    Book::Hebrews,
    Book::James,
    Book::Peter1,
    Book::Peter2,
    Book::John1,
    Book::John2,
    Book::John3,
    Book::Jude,
    Book::Revelation,
];

/// Struktura reprezentující pasáž v Bibli. Celá pasáž je v jednom překladu,
/// ale může se rozkládat přes hrany kapitol (např. Jan 21:24 - Skutky 1:2).
///
/// ### Odkazy
/// To, kde se pasáž nachází je určeno dvěma odkazy - počátkem (`from`) a koncem (`to`).
/// Fungují jako [`RangeInclusive`], tedy, pokud `from == to`, znamená to,
/// že pasáž obsahuje jeden verš.
#[derive(Debug, Clone)]
pub struct Passage {
    /// Id překladu v databázi
    translation_id: i64,
    /// Člověkem čitelný název překladu
    translation_name: String,
    /// První verš pasáže
    from: VerseIndex,
    /// Poslední verš pasáže (včetně)
    to: VerseIndex,
    /// Jednotlivé verše ve správném pořadí, reprezentováno dvojicí (číslo_verše, obsah_verše)
    verses: Vec<(u8, String)>,
}

impl Passage {
    /// Načte pasáž od verše `from` po verš `to` (včetně) v překladu identifikovaného
    /// daným `id` z databáze pomocí připojení `conn`. Pokud je `from` až po `to`
    /// nebo je chyba s databází vrací Error.
    pub async fn load(
        from: VerseIndex,
        to: VerseIndex,
        translation_id: i64,
        conn: &mut PoolConnection<Sqlite>,
    ) -> Result<Self> {
        if from > to {
            bail!("Nevalidní rozsah pasáže, {:?} je až po {:?}", from, to);
        }

        let translation_name = query!(
            "SELECT name FROM translations WHERE id = $1",
            translation_id
        )
        .fetch_one(conn.as_mut())
        .await
        .with_context(|| format!("Nepodařilo se načíst překlad s id {translation_id} z databáze"))?
        .name;

        // Zjistíme čísla pořadí, abychom se mohli jednoduše zeptat na rozsah
        let book_number_start = from.book as u8;
        let book_number_end = to.book as u8;

        let verse_order_start = query!(
            "SELECT verse_order FROM verses WHERE translation_id = $1 AND book_id = $2 AND chapter = $3 AND number = $4",
            translation_id,
            book_number_start,
            from.chapter,
            from.verse_number
        )
        .fetch_one(conn.as_mut())
        .await
        .with_context(|| format!("Nepodařilo se načíst pořadové číslo verše na začátku pasáže {:?}", from))?
        .verse_order;

        let verse_order_end = query!(
            "SELECT verse_order FROM verses WHERE translation_id = $1 AND book_id = $2 AND chapter = $3 AND number = $4",
            translation_id,
            book_number_end,
            to.chapter,
            to.verse_number
        )
        .fetch_one(conn.as_mut())
        .await
        .with_context(|| format!("Nepodařilo se načíst pořadové číslo verše na začátku pasáže {:?}", from))?
        .verse_order;

        let verses = query!(
            "SELECT number, content FROM verses WHERE verse_order >= $1 AND verse_order <= $2 AND translation_id = $3",
            verse_order_start,
            verse_order_end,
            translation_id
        )
        .map(|record| (record.number as u8, record.content))
        .fetch_all(conn.as_mut())
        .await
        .with_context(|| format!("Nepodařilo se načíst verše z databáze"))?;

        Ok(Self {
            translation_id,
            translation_name,
            from,
            to,
            verses,
        })
    }

    /// Vrátí read-only referenci pro čtení veršů pasáže
    pub fn get_verses(&self) -> &[(u8, String)] {
        &self.verses
    }

    /// Vrátí rozsah pasáže - dvojici (od, do)
    pub fn get_range(&self) -> (VerseIndex, VerseIndex) {
        (self.from, self.to)
    }

    /// Vrátí název pasáže
    pub fn get_translation_name(&self) -> &str {
        &self.translation_name
    }

    /// Zkontroluje, že rozsah pasáže je validní (první verš je v Bibli "dřív" než poslední)
    fn is_valid(&self) -> bool {
        if self.from > self.to { false } else { true }
    }
}

/// Index jednoznačně identifikující verš v Bibli.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
// Zde můžeme derivenout Eq/Ord, protože se bude porovnávat jedna položka podruhé
// (book -> chapter -> verse), což je přesně, co chceme
pub struct VerseIndex {
    book: Book,
    // Nejdelší kniha má 150 kapitol (žalmy), u8 postačí
    chapter: u8,
    // Nejdelší kniha má 176 veršů (žalm 119), u8 postačí
    verse_number: u8,
}

impl Display for VerseIndex {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} {}:{}", self.book, self.chapter, self.verse_number)
    }
}

impl VerseIndex {
    /// Pokusi se zkonstruovat nový index verše. Pokud taková kombinace knihy,
    /// kapitoly a verše neexistuje, vrátí None.
    pub fn try_new(book: Book, chapter: u8, verse: u8) -> Option<Self> {
        if verses_in_chapter(book, chapter).is_none_or(|range| !range.contains(&verse)) {
            None
        } else {
            Some(Self {
                book,
                chapter,
                verse_number: verse,
            })
        }
    }

    /// Vrátí trojici `(kniha, kapitola, číslo_verše)` v čistě numerické podobě odpovídající
    /// reprezentaci v databázi
    pub fn destructure_numeric(&self) -> (u8, u8, u8) {
        (self.book as u8, self.chapter, self.verse_number)
    }
}

/// Vrátí rozsah veršů kapitoly dané knihy.
///
/// Pokud kniha neobsahuje kapitolu `chapter`, vrátí `None`.
pub fn verses_in_chapter(book: Book, chapter: u8) -> Option<RangeInclusive<u8>> {
    if !chapters_in_book(book).contains(&chapter) {
        return None;
    }

    match (book, chapter) {
        // Starý Zákon
        (Book::Genesis, 1) => Some(1..=31),
        (Book::Genesis, 2) => Some(1..=25),
        (Book::Genesis, 3) => Some(1..=24),
        (Book::Genesis, 4) => Some(1..=26),
        (Book::Genesis, 5) => Some(1..=32),
        (Book::Genesis, 6) => Some(1..=22),
        (Book::Genesis, 7) => Some(1..=24),
        (Book::Genesis, 8) => Some(1..=22),
        (Book::Genesis, 9) => Some(1..=29),
        (Book::Genesis, 10) => Some(1..=32),
        (Book::Genesis, 11) => Some(1..=32),
        (Book::Genesis, 12) => Some(1..=20),
        (Book::Genesis, 13) => Some(1..=18),
        (Book::Genesis, 14) => Some(1..=24),
        (Book::Genesis, 15) => Some(1..=21),
        (Book::Genesis, 16) => Some(1..=16),
        (Book::Genesis, 17) => Some(1..=27),
        (Book::Genesis, 18) => Some(1..=33),
        (Book::Genesis, 19) => Some(1..=38),
        (Book::Genesis, 20) => Some(1..=18),
        (Book::Genesis, 21) => Some(1..=34),
        (Book::Genesis, 22) => Some(1..=24),
        (Book::Genesis, 23) => Some(1..=20),
        (Book::Genesis, 24) => Some(1..=67),
        (Book::Genesis, 25) => Some(1..=34),
        (Book::Genesis, 26) => Some(1..=35),
        (Book::Genesis, 27) => Some(1..=46),
        (Book::Genesis, 28) => Some(1..=22),
        (Book::Genesis, 29) => Some(1..=35),
        (Book::Genesis, 30) => Some(1..=43),
        (Book::Genesis, 31) => Some(1..=54),
        (Book::Genesis, 32) => Some(1..=33),
        (Book::Genesis, 33) => Some(1..=20),
        (Book::Genesis, 34) => Some(1..=31),
        (Book::Genesis, 35) => Some(1..=29),
        (Book::Genesis, 36) => Some(1..=43),
        (Book::Genesis, 37) => Some(1..=36),
        (Book::Genesis, 38) => Some(1..=30),
        (Book::Genesis, 39) => Some(1..=23),
        (Book::Genesis, 40) => Some(1..=23),
        (Book::Genesis, 41) => Some(1..=57),
        (Book::Genesis, 42) => Some(1..=38),
        (Book::Genesis, 43) => Some(1..=34),
        (Book::Genesis, 44) => Some(1..=34),
        (Book::Genesis, 45) => Some(1..=28),
        (Book::Genesis, 46) => Some(1..=34),
        (Book::Genesis, 47) => Some(1..=31),
        (Book::Genesis, 48) => Some(1..=22),
        (Book::Genesis, 49) => Some(1..=33),
        (Book::Genesis, 50) => Some(1..=26),
        (Book::Exodus, 1) => Some(1..=22),
        (Book::Exodus, 2) => Some(1..=25),
        (Book::Exodus, 3) => Some(1..=22),
        (Book::Exodus, 4) => Some(1..=31),
        (Book::Exodus, 5) => Some(1..=23),
        (Book::Exodus, 6) => Some(1..=30),
        (Book::Exodus, 7) => Some(1..=29),
        (Book::Exodus, 8) => Some(1..=28),
        (Book::Exodus, 9) => Some(1..=35),
        (Book::Exodus, 10) => Some(1..=29),
        (Book::Exodus, 11) => Some(1..=10),
        (Book::Exodus, 12) => Some(1..=51),
        (Book::Exodus, 13) => Some(1..=22),
        (Book::Exodus, 14) => Some(1..=31),
        (Book::Exodus, 15) => Some(1..=27),
        (Book::Exodus, 16) => Some(1..=36),
        (Book::Exodus, 17) => Some(1..=16),
        (Book::Exodus, 18) => Some(1..=27),
        (Book::Exodus, 19) => Some(1..=25),
        (Book::Exodus, 20) => Some(1..=26),
        (Book::Exodus, 21) => Some(1..=37),
        (Book::Exodus, 22) => Some(1..=30),
        (Book::Exodus, 23) => Some(1..=33),
        (Book::Exodus, 24) => Some(1..=18),
        (Book::Exodus, 25) => Some(1..=40),
        (Book::Exodus, 26) => Some(1..=37),
        (Book::Exodus, 27) => Some(1..=21),
        (Book::Exodus, 28) => Some(1..=43),
        (Book::Exodus, 29) => Some(1..=46),
        (Book::Exodus, 30) => Some(1..=38),
        (Book::Exodus, 31) => Some(1..=18),
        (Book::Exodus, 32) => Some(1..=35),
        (Book::Exodus, 33) => Some(1..=23),
        (Book::Exodus, 34) => Some(1..=35),
        (Book::Exodus, 35) => Some(1..=35),
        (Book::Exodus, 36) => Some(1..=38),
        (Book::Exodus, 37) => Some(1..=29),
        (Book::Exodus, 38) => Some(1..=31),
        (Book::Exodus, 39) => Some(1..=43),
        (Book::Exodus, 40) => Some(1..=38),
        (Book::Leviticus, 1) => Some(1..=17),
        (Book::Leviticus, 2) => Some(1..=16),
        (Book::Leviticus, 3) => Some(1..=17),
        (Book::Leviticus, 4) => Some(1..=35),
        (Book::Leviticus, 5) => Some(1..=26),
        (Book::Leviticus, 6) => Some(1..=23),
        (Book::Leviticus, 7) => Some(1..=38),
        (Book::Leviticus, 8) => Some(1..=36),
        (Book::Leviticus, 9) => Some(1..=24),
        (Book::Leviticus, 10) => Some(1..=20),
        (Book::Leviticus, 11) => Some(1..=47),
        (Book::Leviticus, 12) => Some(1..=8),
        (Book::Leviticus, 13) => Some(1..=59),
        (Book::Leviticus, 14) => Some(1..=57),
        (Book::Leviticus, 15) => Some(1..=33),
        (Book::Leviticus, 16) => Some(1..=34),
        (Book::Leviticus, 18) => Some(1..=16),
        (Book::Leviticus, 19) => Some(1..=30),
        (Book::Leviticus, 20) => Some(1..=37),
        (Book::Leviticus, 21) => Some(1..=27),
        (Book::Leviticus, 22) => Some(1..=24),
        (Book::Leviticus, 23) => Some(1..=33),
        (Book::Leviticus, 24) => Some(1..=44),
        (Book::Leviticus, 25) => Some(1..=23),
        (Book::Leviticus, 26) => Some(1..=55),
        (Book::Leviticus, 27) => Some(1..=46),
        (Book::Leviticus, 28) => Some(1..=34),
        (Book::Numbers, 1) => Some(1..=54),
        (Book::Numbers, 2) => Some(1..=34),
        (Book::Numbers, 3) => Some(1..=51),
        (Book::Numbers, 4) => Some(1..=49),
        (Book::Numbers, 5) => Some(1..=31),
        (Book::Numbers, 6) => Some(1..=27),
        (Book::Numbers, 7) => Some(1..=89),
        (Book::Numbers, 8) => Some(1..=26),
        (Book::Numbers, 9) => Some(1..=23),
        (Book::Numbers, 10) => Some(1..=36),
        (Book::Numbers, 11) => Some(1..=35),
        (Book::Numbers, 12) => Some(1..=16),
        (Book::Numbers, 13) => Some(1..=33),
        (Book::Numbers, 14) => Some(1..=45),
        (Book::Numbers, 15) => Some(1..=41),
        (Book::Numbers, 16) => Some(1..=35),
        (Book::Numbers, 17) => Some(1..=28),
        (Book::Numbers, 18) => Some(1..=32),
        (Book::Numbers, 19) => Some(1..=22),
        (Book::Numbers, 20) => Some(1..=29),
        (Book::Numbers, 21) => Some(1..=35),
        (Book::Numbers, 22) => Some(1..=41),
        (Book::Numbers, 23) => Some(1..=30),
        (Book::Numbers, 24) => Some(1..=25),
        (Book::Numbers, 25) => Some(1..=19),
        (Book::Numbers, 26) => Some(1..=65),
        (Book::Numbers, 27) => Some(1..=23),
        (Book::Numbers, 28) => Some(1..=31),
        (Book::Numbers, 29) => Some(1..=39),
        (Book::Numbers, 30) => Some(1..=17),
        (Book::Numbers, 31) => Some(1..=54),
        (Book::Numbers, 32) => Some(1..=42),
        (Book::Numbers, 33) => Some(1..=56),
        (Book::Numbers, 34) => Some(1..=29),
        (Book::Numbers, 35) => Some(1..=34),
        (Book::Numbers, 36) => Some(1..=13),
        (Book::Deuteronomy, 1) => Some(1..=46),
        (Book::Deuteronomy, 2) => Some(1..=37),
        (Book::Deuteronomy, 3) => Some(1..=29),
        (Book::Deuteronomy, 4) => Some(1..=49),
        (Book::Deuteronomy, 5) => Some(1..=33),
        (Book::Deuteronomy, 6) => Some(1..=25),
        (Book::Deuteronomy, 7) => Some(1..=26),
        (Book::Deuteronomy, 8) => Some(1..=20),
        (Book::Deuteronomy, 9) => Some(1..=29),
        (Book::Deuteronomy, 10) => Some(1..=22),
        (Book::Deuteronomy, 11) => Some(1..=32),
        (Book::Deuteronomy, 12) => Some(1..=31),
        (Book::Deuteronomy, 13) => Some(1..=19),
        (Book::Deuteronomy, 14) => Some(1..=29),
        (Book::Deuteronomy, 15) => Some(1..=23),
        (Book::Deuteronomy, 16) => Some(1..=22),
        (Book::Deuteronomy, 17) => Some(1..=20),
        (Book::Deuteronomy, 18) => Some(1..=22),
        (Book::Deuteronomy, 19) => Some(1..=21),
        (Book::Deuteronomy, 20) => Some(1..=20),
        (Book::Deuteronomy, 21) => Some(1..=23),
        (Book::Deuteronomy, 22) => Some(1..=29),
        (Book::Deuteronomy, 23) => Some(1..=26),
        (Book::Deuteronomy, 24) => Some(1..=22),
        (Book::Deuteronomy, 25) => Some(1..=19),
        (Book::Deuteronomy, 26) => Some(1..=19),
        (Book::Deuteronomy, 27) => Some(1..=26),
        (Book::Deuteronomy, 28) => Some(1..=69),
        (Book::Deuteronomy, 29) => Some(1..=28),
        (Book::Deuteronomy, 30) => Some(1..=20),
        (Book::Deuteronomy, 31) => Some(1..=30),
        (Book::Deuteronomy, 32) => Some(1..=52),
        (Book::Deuteronomy, 33) => Some(1..=29),
        (Book::Deuteronomy, 34) => Some(1..=12),
        (Book::Joshua, 1) => Some(1..=18),
        (Book::Joshua, 2) => Some(1..=24),
        (Book::Joshua, 3) => Some(1..=17),
        (Book::Joshua, 4) => Some(1..=24),
        (Book::Joshua, 5) => Some(1..=15),
        (Book::Joshua, 6) => Some(1..=27),
        (Book::Joshua, 7) => Some(1..=26),
        (Book::Joshua, 8) => Some(1..=35),
        (Book::Joshua, 9) => Some(1..=27),
        (Book::Joshua, 10) => Some(1..=43),
        (Book::Joshua, 11) => Some(1..=23),
        (Book::Joshua, 12) => Some(1..=24),
        (Book::Joshua, 13) => Some(1..=33),
        (Book::Joshua, 14) => Some(1..=15),
        (Book::Joshua, 15) => Some(1..=63),
        (Book::Joshua, 16) => Some(1..=10),
        (Book::Joshua, 17) => Some(1..=18),
        (Book::Joshua, 18) => Some(1..=28),
        (Book::Joshua, 19) => Some(1..=51),
        (Book::Joshua, 20) => Some(1..=9),
        (Book::Joshua, 21) => Some(1..=45),
        (Book::Joshua, 22) => Some(1..=34),
        (Book::Joshua, 23) => Some(1..=16),
        (Book::Joshua, 24) => Some(1..=33),
        (Book::Judges, 1) => Some(1..=36),
        (Book::Judges, 2) => Some(1..=23),
        (Book::Judges, 3) => Some(1..=31),
        (Book::Judges, 4) => Some(1..=24),
        (Book::Judges, 5) => Some(1..=31),
        (Book::Judges, 6) => Some(1..=40),
        (Book::Judges, 7) => Some(1..=25),
        (Book::Judges, 8) => Some(1..=35),
        (Book::Judges, 9) => Some(1..=57),
        (Book::Judges, 10) => Some(1..=18),
        (Book::Judges, 11) => Some(1..=40),
        (Book::Judges, 12) => Some(1..=15),
        (Book::Judges, 13) => Some(1..=25),
        (Book::Judges, 14) => Some(1..=20),
        (Book::Judges, 15) => Some(1..=20),
        (Book::Judges, 16) => Some(1..=31),
        (Book::Judges, 17) => Some(1..=13),
        (Book::Judges, 18) => Some(1..=31),
        (Book::Judges, 19) => Some(1..=30),
        (Book::Judges, 20) => Some(1..=48),
        (Book::Judges, 21) => Some(1..=25),
        (Book::Ruth, 1) => Some(1..=22),
        (Book::Ruth, 2) => Some(1..=23),
        (Book::Ruth, 3) => Some(1..=18),
        (Book::Ruth, 4) => Some(1..=22),
        (Book::Samuel1, 1) => Some(1..=28),
        (Book::Samuel1, 2) => Some(1..=36),
        (Book::Samuel1, 3) => Some(1..=21),
        (Book::Samuel1, 4) => Some(1..=22),
        (Book::Samuel1, 5) => Some(1..=12),
        (Book::Samuel1, 6) => Some(1..=21),
        (Book::Samuel1, 7) => Some(1..=17),
        (Book::Samuel1, 8) => Some(1..=22),
        (Book::Samuel1, 9) => Some(1..=27),
        (Book::Samuel1, 10) => Some(1..=27),
        (Book::Samuel1, 11) => Some(1..=15),
        (Book::Samuel1, 12) => Some(1..=25),
        (Book::Samuel1, 13) => Some(1..=23),
        (Book::Samuel1, 14) => Some(1..=52),
        (Book::Samuel1, 15) => Some(1..=35),
        (Book::Samuel1, 16) => Some(1..=23),
        (Book::Samuel1, 17) => Some(1..=58),
        (Book::Samuel1, 18) => Some(1..=30),
        (Book::Samuel1, 19) => Some(1..=24),
        (Book::Samuel1, 20) => Some(1..=42),
        (Book::Samuel1, 21) => Some(1..=16),
        (Book::Samuel1, 22) => Some(1..=23),
        (Book::Samuel1, 23) => Some(1..=28),
        (Book::Samuel1, 24) => Some(1..=23),
        (Book::Samuel1, 25) => Some(1..=43),
        (Book::Samuel1, 26) => Some(1..=25),
        (Book::Samuel1, 27) => Some(1..=12),
        (Book::Samuel1, 28) => Some(1..=25),
        (Book::Samuel1, 29) => Some(1..=11),
        (Book::Samuel1, 30) => Some(1..=31),
        (Book::Samuel1, 31) => Some(1..=13),
        (Book::Samuel2, 1) => Some(1..=27),
        (Book::Samuel2, 2) => Some(1..=32),
        (Book::Samuel2, 3) => Some(1..=39),
        (Book::Samuel2, 4) => Some(1..=12),
        (Book::Samuel2, 5) => Some(1..=25),
        (Book::Samuel2, 6) => Some(1..=23),
        (Book::Samuel2, 7) => Some(1..=29),
        (Book::Samuel2, 8) => Some(1..=18),
        (Book::Samuel2, 9) => Some(1..=13),
        (Book::Samuel2, 10) => Some(1..=19),
        (Book::Samuel2, 11) => Some(1..=27),
        (Book::Samuel2, 12) => Some(1..=31),
        (Book::Samuel2, 13) => Some(1..=39),
        (Book::Samuel2, 14) => Some(1..=33),
        (Book::Samuel2, 15) => Some(1..=37),
        (Book::Samuel2, 16) => Some(1..=23),
        (Book::Samuel2, 17) => Some(1..=29),
        (Book::Samuel2, 18) => Some(1..=32),
        (Book::Samuel2, 19) => Some(1..=44),
        (Book::Samuel2, 20) => Some(1..=26),
        (Book::Samuel2, 21) => Some(1..=22),
        (Book::Samuel2, 22) => Some(1..=51),
        (Book::Samuel2, 23) => Some(1..=39),
        (Book::Samuel2, 24) => Some(1..=25),
        (Book::Kings1, 1) => Some(1..=53),
        (Book::Kings1, 2) => Some(1..=46),
        (Book::Kings1, 3) => Some(1..=28),
        (Book::Kings1, 4) => Some(1..=20),
        (Book::Kings1, 5) => Some(1..=32),
        (Book::Kings1, 6) => Some(1..=38),
        (Book::Kings1, 7) => Some(1..=51),
        (Book::Kings1, 8) => Some(1..=66),
        (Book::Kings1, 9) => Some(1..=28),
        (Book::Kings1, 10) => Some(1..=29),
        (Book::Kings1, 11) => Some(1..=43),
        (Book::Kings1, 12) => Some(1..=33),
        (Book::Kings1, 13) => Some(1..=34),
        (Book::Kings1, 14) => Some(1..=31),
        (Book::Kings1, 15) => Some(1..=34),
        (Book::Kings1, 16) => Some(1..=34),
        (Book::Kings1, 17) => Some(1..=24),
        (Book::Kings1, 18) => Some(1..=46),
        (Book::Kings1, 19) => Some(1..=21),
        (Book::Kings1, 20) => Some(1..=43),
        (Book::Kings1, 21) => Some(1..=29),
        (Book::Kings1, 22) => Some(1..=54),
        (Book::Kings2, 1) => Some(1..=18),
        (Book::Kings2, 2) => Some(1..=25),
        (Book::Kings2, 3) => Some(1..=27),
        (Book::Kings2, 4) => Some(1..=44),
        (Book::Kings2, 5) => Some(1..=27),
        (Book::Kings2, 6) => Some(1..=33),
        (Book::Kings2, 7) => Some(1..=20),
        (Book::Kings2, 8) => Some(1..=29),
        (Book::Kings2, 9) => Some(1..=37),
        (Book::Kings2, 10) => Some(1..=36),
        (Book::Kings2, 11) => Some(1..=20),
        (Book::Kings2, 12) => Some(1..=22),
        (Book::Kings2, 13) => Some(1..=25),
        (Book::Kings2, 14) => Some(1..=29),
        (Book::Kings2, 15) => Some(1..=38),
        (Book::Kings2, 16) => Some(1..=20),
        (Book::Kings2, 17) => Some(1..=41),
        (Book::Kings2, 18) => Some(1..=37),
        (Book::Kings2, 19) => Some(1..=37),
        (Book::Kings2, 20) => Some(1..=21),
        (Book::Kings2, 21) => Some(1..=26),
        (Book::Kings2, 22) => Some(1..=20),
        (Book::Kings2, 23) => Some(1..=37),
        (Book::Kings2, 24) => Some(1..=20),
        (Book::Kings2, 25) => Some(1..=30),
        (Book::Chronicles1, 1) => Some(1..=54),
        (Book::Chronicles1, 2) => Some(1..=55),
        (Book::Chronicles1, 3) => Some(1..=24),
        (Book::Chronicles1, 4) => Some(1..=43),
        (Book::Chronicles1, 5) => Some(1..=41),
        (Book::Chronicles1, 6) => Some(1..=66),
        (Book::Chronicles1, 7) => Some(1..=40),
        (Book::Chronicles1, 8) => Some(1..=40),
        (Book::Chronicles1, 9) => Some(1..=44),
        (Book::Chronicles1, 10) => Some(1..=14),
        (Book::Chronicles1, 11) => Some(1..=47),
        (Book::Chronicles1, 12) => Some(1..=41),
        (Book::Chronicles1, 13) => Some(1..=14),
        (Book::Chronicles1, 14) => Some(1..=17),
        (Book::Chronicles1, 15) => Some(1..=29),
        (Book::Chronicles1, 16) => Some(1..=43),
        (Book::Chronicles1, 17) => Some(1..=27),
        (Book::Chronicles1, 18) => Some(1..=17),
        (Book::Chronicles1, 19) => Some(1..=19),
        (Book::Chronicles1, 20) => Some(1..=8),
        (Book::Chronicles1, 21) => Some(1..=30),
        (Book::Chronicles1, 22) => Some(1..=19),
        (Book::Chronicles1, 23) => Some(1..=32),
        (Book::Chronicles1, 24) => Some(1..=31),
        (Book::Chronicles1, 25) => Some(1..=31),
        (Book::Chronicles1, 26) => Some(1..=32),
        (Book::Chronicles1, 27) => Some(1..=34),
        (Book::Chronicles1, 28) => Some(1..=21),
        (Book::Chronicles1, 29) => Some(1..=30),
        (Book::Chronicles2, 1) => Some(1..=18),
        (Book::Chronicles2, 2) => Some(1..=17),
        (Book::Chronicles2, 3) => Some(1..=17),
        (Book::Chronicles2, 4) => Some(1..=22),
        (Book::Chronicles2, 5) => Some(1..=14),
        (Book::Chronicles2, 6) => Some(1..=42),
        (Book::Chronicles2, 7) => Some(1..=22),
        (Book::Chronicles2, 8) => Some(1..=18),
        (Book::Chronicles2, 9) => Some(1..=31),
        (Book::Chronicles2, 10) => Some(1..=19),
        (Book::Chronicles2, 11) => Some(1..=23),
        (Book::Chronicles2, 12) => Some(1..=16),
        (Book::Chronicles2, 13) => Some(1..=23),
        (Book::Chronicles2, 14) => Some(1..=14),
        (Book::Chronicles2, 15) => Some(1..=19),
        (Book::Chronicles2, 16) => Some(1..=14),
        (Book::Chronicles2, 17) => Some(1..=19),
        (Book::Chronicles2, 18) => Some(1..=34),
        (Book::Chronicles2, 19) => Some(1..=11),
        (Book::Chronicles2, 20) => Some(1..=37),
        (Book::Chronicles2, 21) => Some(1..=20),
        (Book::Chronicles2, 22) => Some(1..=12),
        (Book::Chronicles2, 23) => Some(1..=21),
        (Book::Chronicles2, 24) => Some(1..=27),
        (Book::Chronicles2, 25) => Some(1..=28),
        (Book::Chronicles2, 26) => Some(1..=23),
        (Book::Chronicles2, 27) => Some(1..=9),
        (Book::Chronicles2, 28) => Some(1..=27),
        (Book::Chronicles2, 29) => Some(1..=36),
        (Book::Chronicles2, 30) => Some(1..=27),
        (Book::Chronicles2, 31) => Some(1..=21),
        (Book::Chronicles2, 32) => Some(1..=33),
        (Book::Chronicles2, 33) => Some(1..=25),
        (Book::Chronicles2, 34) => Some(1..=33),
        (Book::Chronicles2, 35) => Some(1..=26),
        (Book::Chronicles2, 36) => Some(1..=23),
        (Book::Ezra, 1) => Some(1..=11),
        (Book::Ezra, 2) => Some(1..=70),
        (Book::Ezra, 3) => Some(1..=13),
        (Book::Ezra, 4) => Some(1..=24),
        (Book::Ezra, 5) => Some(1..=17),
        (Book::Ezra, 6) => Some(1..=22),
        (Book::Ezra, 7) => Some(1..=28),
        (Book::Ezra, 8) => Some(1..=36),
        (Book::Ezra, 9) => Some(1..=15),
        (Book::Ezra, 10) => Some(1..=44),
        (Book::Nehemiah, 1) => Some(1..=11),
        (Book::Nehemiah, 2) => Some(1..=20),
        (Book::Nehemiah, 3) => Some(1..=38),
        (Book::Nehemiah, 4) => Some(1..=17),
        (Book::Nehemiah, 5) => Some(1..=19),
        (Book::Nehemiah, 6) => Some(1..=19),
        (Book::Nehemiah, 7) => Some(1..=72),
        (Book::Nehemiah, 8) => Some(1..=18),
        (Book::Nehemiah, 9) => Some(1..=37),
        (Book::Nehemiah, 10) => Some(1..=40),
        (Book::Nehemiah, 11) => Some(1..=36),
        (Book::Nehemiah, 12) => Some(1..=47),
        (Book::Nehemiah, 13) => Some(1..=31),
        (Book::Esther, 1) => Some(1..=22),
        (Book::Esther, 2) => Some(1..=23),
        (Book::Esther, 3) => Some(1..=15),
        (Book::Esther, 4) => Some(1..=17),
        (Book::Esther, 5) => Some(1..=14),
        (Book::Esther, 6) => Some(1..=14),
        (Book::Esther, 7) => Some(1..=10),
        (Book::Esther, 8) => Some(1..=17),
        (Book::Esther, 9) => Some(1..=32),
        (Book::Esther, 10) => Some(1..=3),
        (Book::Job, 1) => Some(1..=22),
        (Book::Job, 2) => Some(1..=13),
        (Book::Job, 3) => Some(1..=26),
        (Book::Job, 4) => Some(1..=21),
        (Book::Job, 5) => Some(1..=27),
        (Book::Job, 6) => Some(1..=30),
        (Book::Job, 7) => Some(1..=21),
        (Book::Job, 8) => Some(1..=22),
        (Book::Job, 9) => Some(1..=35),
        (Book::Job, 10) => Some(1..=22),
        (Book::Job, 11) => Some(1..=20),
        (Book::Job, 12) => Some(1..=25),
        (Book::Job, 13) => Some(1..=28),
        (Book::Job, 14) => Some(1..=22),
        (Book::Job, 15) => Some(1..=35),
        (Book::Job, 16) => Some(1..=22),
        (Book::Job, 17) => Some(1..=16),
        (Book::Job, 18) => Some(1..=21),
        (Book::Job, 19) => Some(1..=29),
        (Book::Job, 20) => Some(1..=29),
        (Book::Job, 21) => Some(1..=34),
        (Book::Job, 22) => Some(1..=30),
        (Book::Job, 23) => Some(1..=17),
        (Book::Job, 24) => Some(1..=25),
        (Book::Job, 25) => Some(1..=6),
        (Book::Job, 26) => Some(1..=14),
        (Book::Job, 27) => Some(1..=21),
        (Book::Job, 28) => Some(1..=28),
        (Book::Job, 29) => Some(1..=25),
        (Book::Job, 30) => Some(1..=31),
        (Book::Job, 31) => Some(1..=40),
        (Book::Job, 32) => Some(1..=22),
        (Book::Job, 33) => Some(1..=33),
        (Book::Job, 34) => Some(1..=37),
        (Book::Job, 35) => Some(1..=16),
        (Book::Job, 36) => Some(1..=33),
        (Book::Job, 37) => Some(1..=24),
        (Book::Job, 38) => Some(1..=41),
        (Book::Job, 39) => Some(1..=30),
        (Book::Job, 40) => Some(1..=32),
        (Book::Job, 41) => Some(1..=26),
        (Book::Job, 42) => Some(1..=17),
        (Book::Psalms, 1) => Some(1..=6),
        (Book::Psalms, 2) => Some(1..=12),
        (Book::Psalms, 3) => Some(1..=9),
        (Book::Psalms, 4) => Some(1..=9),
        (Book::Psalms, 5) => Some(1..=13),
        (Book::Psalms, 6) => Some(1..=11),
        (Book::Psalms, 7) => Some(1..=18),
        (Book::Psalms, 8) => Some(1..=10),
        (Book::Psalms, 9) => Some(1..=21),
        (Book::Psalms, 10) => Some(1..=18),
        (Book::Psalms, 11) => Some(1..=7),
        (Book::Psalms, 12) => Some(1..=9),
        (Book::Psalms, 13) => Some(1..=6),
        (Book::Psalms, 14) => Some(1..=7),
        (Book::Psalms, 15) => Some(1..=5),
        (Book::Psalms, 16) => Some(1..=11),
        (Book::Psalms, 17) => Some(1..=15),
        (Book::Psalms, 18) => Some(1..=51),
        (Book::Psalms, 19) => Some(1..=15),
        (Book::Psalms, 20) => Some(1..=10),
        (Book::Psalms, 21) => Some(1..=14),
        (Book::Psalms, 22) => Some(1..=32),
        (Book::Psalms, 23) => Some(1..=6),
        (Book::Psalms, 24) => Some(1..=10),
        (Book::Psalms, 25) => Some(1..=22),
        (Book::Psalms, 26) => Some(1..=11),
        (Book::Psalms, 27) => Some(1..=14),
        (Book::Psalms, 28) => Some(1..=9),
        (Book::Psalms, 29) => Some(1..=11),
        (Book::Psalms, 30) => Some(1..=13),
        (Book::Psalms, 31) => Some(1..=25),
        (Book::Psalms, 32) => Some(1..=11),
        (Book::Psalms, 33) => Some(1..=22),
        (Book::Psalms, 34) => Some(1..=23),
        (Book::Psalms, 35) => Some(1..=28),
        (Book::Psalms, 36) => Some(1..=13),
        (Book::Psalms, 37) => Some(1..=40),
        (Book::Psalms, 38) => Some(1..=23),
        (Book::Psalms, 39) => Some(1..=14),
        (Book::Psalms, 40) => Some(1..=18),
        (Book::Psalms, 41) => Some(1..=14),
        (Book::Psalms, 42) => Some(1..=12),
        (Book::Psalms, 43) => Some(1..=5),
        (Book::Psalms, 44) => Some(1..=27),
        (Book::Psalms, 45) => Some(1..=18),
        (Book::Psalms, 46) => Some(1..=12),
        (Book::Psalms, 47) => Some(1..=10),
        (Book::Psalms, 48) => Some(1..=15),
        (Book::Psalms, 49) => Some(1..=21),
        (Book::Psalms, 50) => Some(1..=23),
        (Book::Psalms, 51) => Some(1..=21),
        (Book::Psalms, 52) => Some(1..=11),
        (Book::Psalms, 53) => Some(1..=7),
        (Book::Psalms, 54) => Some(1..=9),
        (Book::Psalms, 55) => Some(1..=24),
        (Book::Psalms, 56) => Some(1..=14),
        (Book::Psalms, 57) => Some(1..=12),
        (Book::Psalms, 58) => Some(1..=12),
        (Book::Psalms, 59) => Some(1..=18),
        (Book::Psalms, 60) => Some(1..=14),
        (Book::Psalms, 61) => Some(1..=9),
        (Book::Psalms, 62) => Some(1..=13),
        (Book::Psalms, 63) => Some(1..=12),
        (Book::Psalms, 64) => Some(1..=11),
        (Book::Psalms, 65) => Some(1..=14),
        (Book::Psalms, 66) => Some(1..=20),
        (Book::Psalms, 67) => Some(1..=8),
        (Book::Psalms, 68) => Some(1..=36),
        (Book::Psalms, 69) => Some(1..=37),
        (Book::Psalms, 70) => Some(1..=6),
        (Book::Psalms, 71) => Some(1..=24),
        (Book::Psalms, 72) => Some(1..=20),
        (Book::Psalms, 73) => Some(1..=28),
        (Book::Psalms, 74) => Some(1..=23),
        (Book::Psalms, 75) => Some(1..=11),
        (Book::Psalms, 76) => Some(1..=13),
        (Book::Psalms, 77) => Some(1..=21),
        (Book::Psalms, 78) => Some(1..=72),
        (Book::Psalms, 79) => Some(1..=13),
        (Book::Psalms, 80) => Some(1..=20),
        (Book::Psalms, 81) => Some(1..=17),
        (Book::Psalms, 82) => Some(1..=8),
        (Book::Psalms, 83) => Some(1..=19),
        (Book::Psalms, 84) => Some(1..=13),
        (Book::Psalms, 85) => Some(1..=14),
        (Book::Psalms, 86) => Some(1..=17),
        (Book::Psalms, 87) => Some(1..=7),
        (Book::Psalms, 88) => Some(1..=19),
        (Book::Psalms, 89) => Some(1..=53),
        (Book::Psalms, 90) => Some(1..=17),
        (Book::Psalms, 91) => Some(1..=16),
        (Book::Psalms, 92) => Some(1..=16),
        (Book::Psalms, 93) => Some(1..=5),
        (Book::Psalms, 94) => Some(1..=23),
        (Book::Psalms, 95) => Some(1..=11),
        (Book::Psalms, 96) => Some(1..=13),
        (Book::Psalms, 97) => Some(1..=12),
        (Book::Psalms, 98) => Some(1..=9),
        (Book::Psalms, 99) => Some(1..=9),
        (Book::Psalms, 100) => Some(1..=5),
        (Book::Psalms, 101) => Some(1..=8),
        (Book::Psalms, 102) => Some(1..=29),
        (Book::Psalms, 103) => Some(1..=22),
        (Book::Psalms, 104) => Some(1..=35),
        (Book::Psalms, 105) => Some(1..=45),
        (Book::Psalms, 106) => Some(1..=48),
        (Book::Psalms, 107) => Some(1..=43),
        (Book::Psalms, 108) => Some(1..=14),
        (Book::Psalms, 109) => Some(1..=31),
        (Book::Psalms, 110) => Some(1..=7),
        (Book::Psalms, 111) => Some(1..=10),
        (Book::Psalms, 112) => Some(1..=10),
        (Book::Psalms, 113) => Some(1..=9),
        (Book::Psalms, 114) => Some(1..=8),
        (Book::Psalms, 115) => Some(1..=18),
        (Book::Psalms, 116) => Some(1..=19),
        (Book::Psalms, 117) => Some(1..=2),
        (Book::Psalms, 118) => Some(1..=29),
        (Book::Psalms, 119) => Some(1..=176),
        (Book::Psalms, 120) => Some(1..=7),
        (Book::Psalms, 121) => Some(1..=8),
        (Book::Psalms, 122) => Some(1..=9),
        (Book::Psalms, 123) => Some(1..=4),
        (Book::Psalms, 124) => Some(1..=8),
        (Book::Psalms, 125) => Some(1..=5),
        (Book::Psalms, 126) => Some(1..=6),
        (Book::Psalms, 127) => Some(1..=5),
        (Book::Psalms, 128) => Some(1..=6),
        (Book::Psalms, 129) => Some(1..=8),
        (Book::Psalms, 130) => Some(1..=8),
        (Book::Psalms, 131) => Some(1..=3),
        (Book::Psalms, 132) => Some(1..=18),
        (Book::Psalms, 133) => Some(1..=3),
        (Book::Psalms, 134) => Some(1..=3),
        (Book::Psalms, 135) => Some(1..=21),
        (Book::Psalms, 136) => Some(1..=26),
        (Book::Psalms, 137) => Some(1..=9),
        (Book::Psalms, 138) => Some(1..=8),
        (Book::Psalms, 139) => Some(1..=24),
        (Book::Psalms, 140) => Some(1..=14),
        (Book::Psalms, 141) => Some(1..=10),
        (Book::Psalms, 142) => Some(1..=8),
        (Book::Psalms, 143) => Some(1..=12),
        (Book::Psalms, 144) => Some(1..=15),
        (Book::Psalms, 145) => Some(1..=21),
        (Book::Psalms, 146) => Some(1..=10),
        (Book::Psalms, 147) => Some(1..=20),
        (Book::Psalms, 148) => Some(1..=14),
        (Book::Psalms, 149) => Some(1..=9),
        (Book::Psalms, 150) => Some(1..=6),
        (Book::Proverbs, 1) => Some(1..=33),
        (Book::Proverbs, 2) => Some(1..=22),
        (Book::Proverbs, 3) => Some(1..=35),
        (Book::Proverbs, 4) => Some(1..=27),
        (Book::Proverbs, 5) => Some(1..=23),
        (Book::Proverbs, 6) => Some(1..=35),
        (Book::Proverbs, 7) => Some(1..=27),
        (Book::Proverbs, 8) => Some(1..=36),
        (Book::Proverbs, 9) => Some(1..=18),
        (Book::Proverbs, 10) => Some(1..=32),
        (Book::Proverbs, 11) => Some(1..=31),
        (Book::Proverbs, 12) => Some(1..=28),
        (Book::Proverbs, 13) => Some(1..=25),
        (Book::Proverbs, 14) => Some(1..=35),
        (Book::Proverbs, 15) => Some(1..=33),
        (Book::Proverbs, 16) => Some(1..=33),
        (Book::Proverbs, 17) => Some(1..=28),
        (Book::Proverbs, 18) => Some(1..=24),
        (Book::Proverbs, 19) => Some(1..=29),
        (Book::Proverbs, 20) => Some(1..=30),
        (Book::Proverbs, 21) => Some(1..=31),
        (Book::Proverbs, 22) => Some(1..=29),
        (Book::Proverbs, 23) => Some(1..=35),
        (Book::Proverbs, 24) => Some(1..=34),
        (Book::Proverbs, 25) => Some(1..=28),
        (Book::Proverbs, 26) => Some(1..=28),
        (Book::Proverbs, 27) => Some(1..=27),
        (Book::Proverbs, 28) => Some(1..=28),
        (Book::Proverbs, 29) => Some(1..=27),
        (Book::Proverbs, 30) => Some(1..=33),
        (Book::Proverbs, 31) => Some(1..=31),
        (Book::Ecclesiastes, 1) => Some(1..=18),
        (Book::Ecclesiastes, 2) => Some(1..=26),
        (Book::Ecclesiastes, 3) => Some(1..=22),
        (Book::Ecclesiastes, 4) => Some(1..=17),
        (Book::Ecclesiastes, 5) => Some(1..=19),
        (Book::Ecclesiastes, 6) => Some(1..=12),
        (Book::Ecclesiastes, 7) => Some(1..=29),
        (Book::Ecclesiastes, 8) => Some(1..=17),
        (Book::Ecclesiastes, 9) => Some(1..=18),
        (Book::Ecclesiastes, 10) => Some(1..=20),
        (Book::Ecclesiastes, 11) => Some(1..=10),
        (Book::Ecclesiastes, 12) => Some(1..=14),
        (Book::SongOfSolomon, 1) => Some(1..=17),
        (Book::SongOfSolomon, 2) => Some(1..=17),
        (Book::SongOfSolomon, 3) => Some(1..=11),
        (Book::SongOfSolomon, 4) => Some(1..=16),
        (Book::SongOfSolomon, 5) => Some(1..=16),
        (Book::SongOfSolomon, 6) => Some(1..=12),
        (Book::SongOfSolomon, 7) => Some(1..=14),
        (Book::SongOfSolomon, 8) => Some(1..=14),
        (Book::Isaiah, 1) => Some(1..=31),
        (Book::Isaiah, 2) => Some(1..=22),
        (Book::Isaiah, 3) => Some(1..=26),
        (Book::Isaiah, 4) => Some(1..=6),
        (Book::Isaiah, 5) => Some(1..=30),
        (Book::Isaiah, 6) => Some(1..=13),
        (Book::Isaiah, 7) => Some(1..=25),
        (Book::Isaiah, 8) => Some(1..=23),
        (Book::Isaiah, 9) => Some(1..=20),
        (Book::Isaiah, 10) => Some(1..=34),
        (Book::Isaiah, 11) => Some(1..=16),
        (Book::Isaiah, 12) => Some(1..=6),
        (Book::Isaiah, 13) => Some(1..=22),
        (Book::Isaiah, 14) => Some(1..=32),
        (Book::Isaiah, 15) => Some(1..=9),
        (Book::Isaiah, 16) => Some(1..=14),
        (Book::Isaiah, 17) => Some(1..=14),
        (Book::Isaiah, 18) => Some(1..=7),
        (Book::Isaiah, 19) => Some(1..=25),
        (Book::Isaiah, 20) => Some(1..=6),
        (Book::Isaiah, 21) => Some(1..=17),
        (Book::Isaiah, 22) => Some(1..=25),
        (Book::Isaiah, 23) => Some(1..=18),
        (Book::Isaiah, 24) => Some(1..=23),
        (Book::Isaiah, 25) => Some(1..=12),
        (Book::Isaiah, 26) => Some(1..=21),
        (Book::Isaiah, 27) => Some(1..=13),
        (Book::Isaiah, 28) => Some(1..=29),
        (Book::Isaiah, 29) => Some(1..=24),
        (Book::Isaiah, 30) => Some(1..=33),
        (Book::Isaiah, 31) => Some(1..=9),
        (Book::Isaiah, 32) => Some(1..=20),
        (Book::Isaiah, 33) => Some(1..=24),
        (Book::Isaiah, 34) => Some(1..=17),
        (Book::Isaiah, 35) => Some(1..=10),
        (Book::Isaiah, 36) => Some(1..=22),
        (Book::Isaiah, 37) => Some(1..=38),
        (Book::Isaiah, 38) => Some(1..=22),
        (Book::Isaiah, 39) => Some(1..=8),
        (Book::Isaiah, 40) => Some(1..=31),
        (Book::Isaiah, 41) => Some(1..=29),
        (Book::Isaiah, 42) => Some(1..=25),
        (Book::Isaiah, 43) => Some(1..=28),
        (Book::Isaiah, 44) => Some(1..=28),
        (Book::Isaiah, 45) => Some(1..=25),
        (Book::Isaiah, 46) => Some(1..=13),
        (Book::Isaiah, 47) => Some(1..=15),
        (Book::Isaiah, 48) => Some(1..=22),
        (Book::Isaiah, 49) => Some(1..=26),
        (Book::Isaiah, 50) => Some(1..=11),
        (Book::Isaiah, 51) => Some(1..=23),
        (Book::Isaiah, 52) => Some(1..=15),
        (Book::Isaiah, 53) => Some(1..=12),
        (Book::Isaiah, 54) => Some(1..=17),
        (Book::Isaiah, 55) => Some(1..=13),
        (Book::Isaiah, 56) => Some(1..=12),
        (Book::Isaiah, 57) => Some(1..=21),
        (Book::Isaiah, 58) => Some(1..=14),
        (Book::Isaiah, 59) => Some(1..=21),
        (Book::Isaiah, 60) => Some(1..=22),
        (Book::Isaiah, 61) => Some(1..=11),
        (Book::Isaiah, 62) => Some(1..=12),
        (Book::Isaiah, 63) => Some(1..=19),
        (Book::Isaiah, 64) => Some(1..=11),
        (Book::Isaiah, 65) => Some(1..=25),
        (Book::Isaiah, 66) => Some(1..=24),
        (Book::Jeremiah, 1) => Some(1..=19),
        (Book::Jeremiah, 2) => Some(1..=37),
        (Book::Jeremiah, 3) => Some(1..=25),
        (Book::Jeremiah, 4) => Some(1..=31),
        (Book::Jeremiah, 5) => Some(1..=31),
        (Book::Jeremiah, 6) => Some(1..=30),
        (Book::Jeremiah, 7) => Some(1..=34),
        (Book::Jeremiah, 8) => Some(1..=23),
        (Book::Jeremiah, 9) => Some(1..=25),
        (Book::Jeremiah, 10) => Some(1..=25),
        (Book::Jeremiah, 11) => Some(1..=23),
        (Book::Jeremiah, 12) => Some(1..=17),
        (Book::Jeremiah, 13) => Some(1..=27),
        (Book::Jeremiah, 14) => Some(1..=22),
        (Book::Jeremiah, 15) => Some(1..=21),
        (Book::Jeremiah, 16) => Some(1..=21),
        (Book::Jeremiah, 17) => Some(1..=27),
        (Book::Jeremiah, 18) => Some(1..=23),
        (Book::Jeremiah, 19) => Some(1..=15),
        (Book::Jeremiah, 20) => Some(1..=18),
        (Book::Jeremiah, 21) => Some(1..=14),
        (Book::Jeremiah, 22) => Some(1..=30),
        (Book::Jeremiah, 23) => Some(1..=40),
        (Book::Jeremiah, 24) => Some(1..=10),
        (Book::Jeremiah, 25) => Some(1..=38),
        (Book::Jeremiah, 26) => Some(1..=24),
        (Book::Jeremiah, 27) => Some(1..=22),
        (Book::Jeremiah, 28) => Some(1..=17),
        (Book::Jeremiah, 29) => Some(1..=32),
        (Book::Jeremiah, 30) => Some(1..=24),
        (Book::Jeremiah, 31) => Some(1..=40),
        (Book::Jeremiah, 32) => Some(1..=44),
        (Book::Jeremiah, 33) => Some(1..=26),
        (Book::Jeremiah, 34) => Some(1..=22),
        (Book::Jeremiah, 35) => Some(1..=19),
        (Book::Jeremiah, 36) => Some(1..=32),
        (Book::Jeremiah, 37) => Some(1..=21),
        (Book::Jeremiah, 38) => Some(1..=28),
        (Book::Jeremiah, 39) => Some(1..=18),
        (Book::Jeremiah, 40) => Some(1..=16),
        (Book::Jeremiah, 41) => Some(1..=18),
        (Book::Jeremiah, 42) => Some(1..=22),
        (Book::Jeremiah, 43) => Some(1..=13),
        (Book::Jeremiah, 44) => Some(1..=30),
        (Book::Jeremiah, 45) => Some(1..=5),
        (Book::Jeremiah, 46) => Some(1..=28),
        (Book::Jeremiah, 47) => Some(1..=7),
        (Book::Jeremiah, 48) => Some(1..=47),
        (Book::Jeremiah, 49) => Some(1..=39),
        (Book::Jeremiah, 50) => Some(1..=46),
        (Book::Jeremiah, 51) => Some(1..=64),
        (Book::Jeremiah, 52) => Some(1..=34),
        (Book::Lamentations, 1) => Some(1..=22),
        (Book::Lamentations, 2) => Some(1..=22),
        (Book::Lamentations, 3) => Some(1..=66),
        (Book::Lamentations, 4) => Some(1..=22),
        (Book::Lamentations, 5) => Some(1..=22),
        (Book::Ezekiel, 1) => Some(1..=28),
        (Book::Ezekiel, 2) => Some(1..=10),
        (Book::Ezekiel, 3) => Some(1..=27),
        (Book::Ezekiel, 4) => Some(1..=17),
        (Book::Ezekiel, 5) => Some(1..=17),
        (Book::Ezekiel, 6) => Some(1..=14),
        (Book::Ezekiel, 7) => Some(1..=27),
        (Book::Ezekiel, 8) => Some(1..=18),
        (Book::Ezekiel, 9) => Some(1..=11),
        (Book::Ezekiel, 10) => Some(1..=22),
        (Book::Ezekiel, 11) => Some(1..=25),
        (Book::Ezekiel, 12) => Some(1..=28),
        (Book::Ezekiel, 13) => Some(1..=23),
        (Book::Ezekiel, 14) => Some(1..=23),
        (Book::Ezekiel, 15) => Some(1..=8),
        (Book::Ezekiel, 16) => Some(1..=63),
        (Book::Ezekiel, 17) => Some(1..=24),
        (Book::Ezekiel, 18) => Some(1..=32),
        (Book::Ezekiel, 19) => Some(1..=14),
        (Book::Ezekiel, 20) => Some(1..=44),
        (Book::Ezekiel, 21) => Some(1..=37),
        (Book::Ezekiel, 22) => Some(1..=31),
        (Book::Ezekiel, 23) => Some(1..=49),
        (Book::Ezekiel, 24) => Some(1..=27),
        (Book::Ezekiel, 25) => Some(1..=17),
        (Book::Ezekiel, 26) => Some(1..=21),
        (Book::Ezekiel, 27) => Some(1..=36),
        (Book::Ezekiel, 28) => Some(1..=26),
        (Book::Ezekiel, 29) => Some(1..=21),
        (Book::Ezekiel, 30) => Some(1..=26),
        (Book::Ezekiel, 31) => Some(1..=18),
        (Book::Ezekiel, 32) => Some(1..=32),
        (Book::Ezekiel, 33) => Some(1..=33),
        (Book::Ezekiel, 34) => Some(1..=31),
        (Book::Ezekiel, 35) => Some(1..=15),
        (Book::Ezekiel, 36) => Some(1..=38),
        (Book::Ezekiel, 37) => Some(1..=28),
        (Book::Ezekiel, 38) => Some(1..=23),
        (Book::Ezekiel, 39) => Some(1..=29),
        (Book::Ezekiel, 40) => Some(1..=49),
        (Book::Ezekiel, 41) => Some(1..=26),
        (Book::Ezekiel, 42) => Some(1..=20),
        (Book::Ezekiel, 43) => Some(1..=27),
        (Book::Ezekiel, 44) => Some(1..=31),
        (Book::Ezekiel, 45) => Some(1..=25),
        (Book::Ezekiel, 46) => Some(1..=24),
        (Book::Ezekiel, 47) => Some(1..=23),
        (Book::Ezekiel, 48) => Some(1..=35),
        (Book::Daniel, 1) => Some(1..=21),
        (Book::Daniel, 2) => Some(1..=49),
        (Book::Daniel, 3) => Some(1..=100),
        (Book::Daniel, 4) => Some(1..=34),
        (Book::Daniel, 5) => Some(1..=30),
        (Book::Daniel, 6) => Some(1..=29),
        (Book::Daniel, 7) => Some(1..=28),
        (Book::Daniel, 8) => Some(1..=27),
        (Book::Daniel, 9) => Some(1..=27),
        (Book::Daniel, 10) => Some(1..=21),
        (Book::Daniel, 11) => Some(1..=45),
        (Book::Daniel, 12) => Some(1..=13),
        (Book::Hosea, 1) => Some(1..=9),
        (Book::Hosea, 2) => Some(1..=25),
        (Book::Hosea, 3) => Some(1..=5),
        (Book::Hosea, 4) => Some(1..=19),
        (Book::Hosea, 5) => Some(1..=15),
        (Book::Hosea, 6) => Some(1..=11),
        (Book::Hosea, 7) => Some(1..=16),
        (Book::Hosea, 8) => Some(1..=14),
        (Book::Hosea, 9) => Some(1..=17),
        (Book::Hosea, 10) => Some(1..=15),
        (Book::Hosea, 11) => Some(1..=11),
        (Book::Hosea, 12) => Some(1..=15),
        (Book::Hosea, 13) => Some(1..=15),
        (Book::Hosea, 14) => Some(1..=10),
        (Book::Joel, 1) => Some(1..=20),
        (Book::Joel, 2) => Some(1..=27),
        (Book::Joel, 3) => Some(1..=5),
        (Book::Joel, 4) => Some(1..=21),
        (Book::Amos, 1) => Some(1..=15),
        (Book::Amos, 2) => Some(1..=16),
        (Book::Amos, 3) => Some(1..=15),
        (Book::Amos, 4) => Some(1..=13),
        (Book::Amos, 5) => Some(1..=27),
        (Book::Amos, 6) => Some(1..=14),
        (Book::Amos, 7) => Some(1..=17),
        (Book::Amos, 8) => Some(1..=14),
        (Book::Amos, 9) => Some(1..=15),
        (Book::Obadiah, 1) => Some(1..=21),
        (Book::Jonah, 1) => Some(1..=16),
        (Book::Jonah, 2) => Some(1..=11),
        (Book::Jonah, 3) => Some(1..=10),
        (Book::Jonah, 4) => Some(1..=11),
        (Book::Micah, 1) => Some(1..=16),
        (Book::Micah, 2) => Some(1..=13),
        (Book::Micah, 3) => Some(1..=12),
        (Book::Micah, 4) => Some(1..=14),
        (Book::Micah, 5) => Some(1..=14),
        (Book::Micah, 6) => Some(1..=16),
        (Book::Micah, 7) => Some(1..=20),
        (Book::Nahum, 1) => Some(1..=14),
        (Book::Nahum, 2) => Some(1..=14),
        (Book::Nahum, 3) => Some(1..=19),
        (Book::Habakkuk, 1) => Some(1..=17),
        (Book::Habakkuk, 2) => Some(1..=20),
        (Book::Habakkuk, 3) => Some(1..=19),
        (Book::Zephaniah, 1) => Some(1..=18),
        (Book::Zephaniah, 2) => Some(1..=15),
        (Book::Zephaniah, 3) => Some(1..=20),
        (Book::Haggai, 1) => Some(1..=15),
        (Book::Haggai, 2) => Some(1..=23),
        (Book::Zechariah, 1) => Some(1..=17),
        (Book::Zechariah, 2) => Some(1..=17),
        (Book::Zechariah, 3) => Some(1..=10),
        (Book::Zechariah, 4) => Some(1..=14),
        (Book::Zechariah, 5) => Some(1..=11),
        (Book::Zechariah, 6) => Some(1..=15),
        (Book::Zechariah, 7) => Some(1..=14),
        (Book::Zechariah, 8) => Some(1..=23),
        (Book::Zechariah, 9) => Some(1..=17),
        (Book::Zechariah, 10) => Some(1..=12),
        (Book::Zechariah, 11) => Some(1..=17),
        (Book::Zechariah, 12) => Some(1..=14),
        (Book::Zechariah, 13) => Some(1..=9),
        (Book::Zechariah, 14) => Some(1..=21),
        (Book::Malachi, 1) => Some(1..=14),
        (Book::Malachi, 2) => Some(1..=17),
        (Book::Malachi, 3) => Some(1..=24),
        // Nový zákon
        (Book::Matthew, 1) => Some(1..=25),
        (Book::Matthew, 2) => Some(1..=23),
        (Book::Matthew, 3) => Some(1..=17),
        (Book::Matthew, 4) => Some(1..=25),
        (Book::Matthew, 5) => Some(1..=48),
        (Book::Matthew, 6) => Some(1..=34),
        (Book::Matthew, 7) => Some(1..=29),
        (Book::Matthew, 8) => Some(1..=34),
        (Book::Matthew, 9) => Some(1..=38),
        (Book::Matthew, 10) => Some(1..=42),
        (Book::Matthew, 11) => Some(1..=30),
        (Book::Matthew, 12) => Some(1..=50),
        (Book::Matthew, 13) => Some(1..=58),
        (Book::Matthew, 14) => Some(1..=36),
        (Book::Matthew, 15) => Some(1..=39),
        (Book::Matthew, 16) => Some(1..=28),
        (Book::Matthew, 17) => Some(1..=27),
        (Book::Matthew, 18) => Some(1..=35),
        (Book::Matthew, 19) => Some(1..=30),
        (Book::Matthew, 20) => Some(1..=34),
        (Book::Matthew, 21) => Some(1..=46),
        (Book::Matthew, 22) => Some(1..=46),
        (Book::Matthew, 23) => Some(1..=39),
        (Book::Matthew, 24) => Some(1..=51),
        (Book::Matthew, 25) => Some(1..=46),
        (Book::Matthew, 26) => Some(1..=75),
        (Book::Matthew, 27) => Some(1..=66),
        (Book::Matthew, 28) => Some(1..=20),
        (Book::Mark, 1) => Some(1..=45),
        (Book::Mark, 2) => Some(1..=28),
        (Book::Mark, 3) => Some(1..=35),
        (Book::Mark, 4) => Some(1..=41),
        (Book::Mark, 5) => Some(1..=43),
        (Book::Mark, 6) => Some(1..=56),
        (Book::Mark, 7) => Some(1..=37),
        (Book::Mark, 8) => Some(1..=38),
        (Book::Mark, 9) => Some(1..=50),
        (Book::Mark, 10) => Some(1..=52),
        (Book::Mark, 11) => Some(1..=33),
        (Book::Mark, 12) => Some(1..=44),
        (Book::Mark, 13) => Some(1..=37),
        (Book::Mark, 14) => Some(1..=72),
        (Book::Mark, 15) => Some(1..=47),
        (Book::Mark, 16) => Some(1..=29),
        (Book::Luke, 1) => Some(1..=80),
        (Book::Luke, 2) => Some(1..=52),
        (Book::Luke, 3) => Some(1..=38),
        (Book::Luke, 4) => Some(1..=44),
        (Book::Luke, 5) => Some(1..=39),
        (Book::Luke, 6) => Some(1..=49),
        (Book::Luke, 7) => Some(1..=50),
        (Book::Luke, 8) => Some(1..=56),
        (Book::Luke, 9) => Some(1..=62),
        (Book::Luke, 10) => Some(1..=42),
        (Book::Luke, 11) => Some(1..=54),
        (Book::Luke, 12) => Some(1..=59),
        (Book::Luke, 13) => Some(1..=35),
        (Book::Luke, 14) => Some(1..=35),
        (Book::Luke, 15) => Some(1..=32),
        (Book::Luke, 16) => Some(1..=31),
        (Book::Luke, 17) => Some(1..=37),
        (Book::Luke, 18) => Some(1..=43),
        (Book::Luke, 19) => Some(1..=48),
        (Book::Luke, 20) => Some(1..=47),
        (Book::Luke, 21) => Some(1..=38),
        (Book::Luke, 22) => Some(1..=71),
        (Book::Luke, 23) => Some(1..=56),
        (Book::Luke, 24) => Some(1..=53),
        (Book::John, 1) => Some(1..=51),
        (Book::John, 2) => Some(1..=25),
        (Book::John, 3) => Some(1..=36),
        (Book::John, 4) => Some(1..=54),
        (Book::John, 5) => Some(1..=47),
        (Book::John, 6) => Some(1..=71),
        (Book::John, 7) => Some(1..=53),
        (Book::John, 8) => Some(1..=59),
        (Book::John, 9) => Some(1..=41),
        (Book::John, 10) => Some(1..=42),
        (Book::John, 11) => Some(1..=57),
        (Book::John, 12) => Some(1..=50),
        (Book::John, 13) => Some(1..=38),
        (Book::John, 14) => Some(1..=31),
        (Book::John, 15) => Some(1..=27),
        (Book::John, 16) => Some(1..=33),
        (Book::John, 17) => Some(1..=26),
        (Book::John, 18) => Some(1..=40),
        (Book::John, 19) => Some(1..=42),
        (Book::John, 20) => Some(1..=31),
        (Book::John, 21) => Some(1..=25),
        (Book::Acts, 1) => Some(1..=26),
        (Book::Acts, 2) => Some(1..=47),
        (Book::Acts, 3) => Some(1..=26),
        (Book::Acts, 4) => Some(1..=37),
        (Book::Acts, 5) => Some(1..=42),
        (Book::Acts, 6) => Some(1..=15),
        (Book::Acts, 7) => Some(1..=60),
        (Book::Acts, 8) => Some(1..=40),
        (Book::Acts, 9) => Some(1..=43),
        (Book::Acts, 10) => Some(1..=48),
        (Book::Acts, 11) => Some(1..=30),
        (Book::Acts, 12) => Some(1..=25),
        (Book::Acts, 13) => Some(1..=52),
        (Book::Acts, 14) => Some(1..=28),
        (Book::Acts, 15) => Some(1..=41),
        (Book::Acts, 16) => Some(1..=40),
        (Book::Acts, 17) => Some(1..=34),
        (Book::Acts, 18) => Some(1..=28),
        (Book::Acts, 19) => Some(1..=40),
        (Book::Acts, 20) => Some(1..=38),
        (Book::Acts, 21) => Some(1..=40),
        (Book::Acts, 22) => Some(1..=30),
        (Book::Acts, 23) => Some(1..=35),
        (Book::Acts, 24) => Some(1..=27),
        (Book::Acts, 25) => Some(1..=27),
        (Book::Acts, 26) => Some(1..=32),
        (Book::Acts, 27) => Some(1..=44),
        (Book::Acts, 28) => Some(1..=31),
        (Book::Romans, 1) => Some(1..=32),
        (Book::Romans, 2) => Some(1..=29),
        (Book::Romans, 3) => Some(1..=31),
        (Book::Romans, 4) => Some(1..=25),
        (Book::Romans, 5) => Some(1..=21),
        (Book::Romans, 6) => Some(1..=23),
        (Book::Romans, 7) => Some(1..=25),
        (Book::Romans, 8) => Some(1..=39),
        (Book::Romans, 9) => Some(1..=33),
        (Book::Romans, 10) => Some(1..=21),
        (Book::Romans, 11) => Some(1..=36),
        (Book::Romans, 12) => Some(1..=21),
        (Book::Romans, 13) => Some(1..=14),
        (Book::Romans, 14) => Some(1..=23),
        (Book::Romans, 15) => Some(1..=33),
        (Book::Romans, 16) => Some(1..=27),
        (Book::Corinthians1, 1) => Some(1..=31),
        (Book::Corinthians1, 2) => Some(1..=16),
        (Book::Corinthians1, 3) => Some(1..=23),
        (Book::Corinthians1, 4) => Some(1..=21),
        (Book::Corinthians1, 5) => Some(1..=13),
        (Book::Corinthians1, 6) => Some(1..=20),
        (Book::Corinthians1, 7) => Some(1..=40),
        (Book::Corinthians1, 8) => Some(1..=13),
        (Book::Corinthians1, 9) => Some(1..=27),
        (Book::Corinthians1, 10) => Some(1..=33),
        (Book::Corinthians1, 11) => Some(1..=34),
        (Book::Corinthians1, 12) => Some(1..=31),
        (Book::Corinthians1, 13) => Some(1..=13),
        (Book::Corinthians1, 14) => Some(1..=40),
        (Book::Corinthians1, 15) => Some(1..=58),
        (Book::Corinthians1, 16) => Some(1..=24),
        (Book::Corinthians2, 1) => Some(1..=24),
        (Book::Corinthians2, 2) => Some(1..=17),
        (Book::Corinthians2, 3) => Some(1..=18),
        (Book::Corinthians2, 4) => Some(1..=18),
        (Book::Corinthians2, 5) => Some(1..=21),
        (Book::Corinthians2, 6) => Some(1..=18),
        (Book::Corinthians2, 7) => Some(1..=16),
        (Book::Corinthians2, 8) => Some(1..=24),
        (Book::Corinthians2, 9) => Some(1..=15),
        (Book::Corinthians2, 10) => Some(1..=18),
        (Book::Corinthians2, 11) => Some(1..=33),
        (Book::Corinthians2, 12) => Some(1..=21),
        (Book::Corinthians2, 13) => Some(1..=13),
        (Book::Galatians, 1) => Some(1..=24),
        (Book::Galatians, 2) => Some(1..=21),
        (Book::Galatians, 3) => Some(1..=29),
        (Book::Galatians, 4) => Some(1..=31),
        (Book::Galatians, 5) => Some(1..=26),
        (Book::Galatians, 6) => Some(1..=18),
        (Book::Ephesians, 1) => Some(1..=23),
        (Book::Ephesians, 2) => Some(1..=22),
        (Book::Ephesians, 3) => Some(1..=21),
        (Book::Ephesians, 4) => Some(1..=32),
        (Book::Ephesians, 5) => Some(1..=33),
        (Book::Ephesians, 6) => Some(1..=24),
        (Book::Philippians, 1) => Some(1..=30),
        (Book::Philippians, 2) => Some(1..=30),
        (Book::Philippians, 3) => Some(1..=21),
        (Book::Philippians, 4) => Some(1..=23),
        (Book::Colossians, 1) => Some(1..=29),
        (Book::Colossians, 2) => Some(1..=23),
        (Book::Colossians, 3) => Some(1..=25),
        (Book::Colossians, 4) => Some(1..=18),
        (Book::Thessalonians1, 1) => Some(1..=10),
        (Book::Thessalonians1, 2) => Some(1..=20),
        (Book::Thessalonians1, 3) => Some(1..=13),
        (Book::Thessalonians1, 4) => Some(1..=18),
        (Book::Thessalonians1, 5) => Some(1..=28),
        (Book::Thessalonians2, 1) => Some(1..=12),
        (Book::Thessalonians2, 2) => Some(1..=17),
        (Book::Thessalonians2, 3) => Some(1..=18),
        (Book::Timothy1, 1) => Some(1..=20),
        (Book::Timothy1, 2) => Some(1..=15),
        (Book::Timothy1, 3) => Some(1..=16),
        (Book::Timothy1, 4) => Some(1..=16),
        (Book::Timothy1, 5) => Some(1..=25),
        (Book::Timothy1, 6) => Some(1..=21),
        (Book::Timothy2, 1) => Some(1..=18),
        (Book::Timothy2, 2) => Some(1..=26),
        (Book::Timothy2, 3) => Some(1..=17),
        (Book::Timothy2, 4) => Some(1..=22),
        (Book::Titus, 1) => Some(1..=16),
        (Book::Titus, 2) => Some(1..=15),
        (Book::Titus, 3) => Some(1..=15),
        (Book::Philemon, 1) => Some(1..=25),
        (Book::Hebrews, 1) => Some(1..=14),
        (Book::Hebrews, 2) => Some(1..=18),
        (Book::Hebrews, 3) => Some(1..=19),
        (Book::Hebrews, 4) => Some(1..=16),
        (Book::Hebrews, 5) => Some(1..=14),
        (Book::Hebrews, 6) => Some(1..=20),
        (Book::Hebrews, 7) => Some(1..=28),
        (Book::Hebrews, 8) => Some(1..=13),
        (Book::Hebrews, 9) => Some(1..=28),
        (Book::Hebrews, 10) => Some(1..=39),
        (Book::Hebrews, 11) => Some(1..=40),
        (Book::Hebrews, 12) => Some(1..=29),
        (Book::Hebrews, 13) => Some(1..=25),
        (Book::James, 1) => Some(1..=27),
        (Book::James, 2) => Some(1..=26),
        (Book::James, 3) => Some(1..=18),
        (Book::James, 4) => Some(1..=17),
        (Book::James, 5) => Some(1..=20),
        (Book::Peter1, 1) => Some(1..=25),
        (Book::Peter1, 2) => Some(1..=25),
        (Book::Peter1, 3) => Some(1..=22),
        (Book::Peter1, 4) => Some(1..=19),
        (Book::Peter1, 5) => Some(1..=14),
        (Book::Peter2, 1) => Some(1..=21),
        (Book::Peter2, 2) => Some(1..=22),
        (Book::Peter2, 3) => Some(1..=18),
        (Book::John1, 1) => Some(1..=10),
        (Book::John1, 2) => Some(1..=29),
        (Book::John1, 3) => Some(1..=24),
        (Book::John1, 4) => Some(1..=21),
        (Book::John1, 5) => Some(1..=21),
        (Book::John2, 1) => Some(1..=13),
        (Book::John3, 1) => Some(1..=15),
        (Book::Jude, 1) => Some(1..=25),
        (Book::Revelation, 1) => Some(1..=20),
        (Book::Revelation, 2) => Some(1..=29),
        (Book::Revelation, 3) => Some(1..=22),
        (Book::Revelation, 4) => Some(1..=11),
        (Book::Revelation, 5) => Some(1..=14),
        (Book::Revelation, 6) => Some(1..=17),
        (Book::Revelation, 7) => Some(1..=17),
        (Book::Revelation, 8) => Some(1..=13),
        (Book::Revelation, 9) => Some(1..=21),
        (Book::Revelation, 10) => Some(1..=11),
        (Book::Revelation, 11) => Some(1..=19),
        (Book::Revelation, 12) => Some(1..=18),
        (Book::Revelation, 13) => Some(1..=18),
        (Book::Revelation, 14) => Some(1..=20),
        (Book::Revelation, 15) => Some(1..=8),
        (Book::Revelation, 16) => Some(1..=21),
        (Book::Revelation, 17) => Some(1..=18),
        (Book::Revelation, 18) => Some(1..=24),
        (Book::Revelation, 19) => Some(1..=21),
        (Book::Revelation, 20) => Some(1..=15),
        (Book::Revelation, 21) => Some(1..=27),
        (Book::Revelation, 22) => Some(1..=21),
        (_, _) => {
            trace!("Nevalidní kapitola: {} knihy {}", chapter, book);
            None
        }
    }
}

/// Vrátí rozsah kapitol v knize
pub fn chapters_in_book(book: Book) -> RangeInclusive<u8> {
    match book {
        Book::Genesis => 1..=50,
        Book::Exodus => 1..=40,
        Book::Leviticus => 1..=27,
        Book::Numbers => 1..=36,
        Book::Deuteronomy => 1..=34,
        Book::Joshua => 1..=24,
        Book::Judges => 1..=21,
        Book::Ruth => 1..=4,
        Book::Samuel1 => 1..=31,
        Book::Samuel2 => 1..=24,
        Book::Kings1 => 1..=22,
        Book::Kings2 => 1..=25,
        Book::Chronicles1 => 1..=29,
        Book::Chronicles2 => 1..=26,
        Book::Ezra => 1..=10,
        Book::Nehemiah => 1..=13,
        Book::Esther => 1..=10,
        Book::Job => 1..=42,
        Book::Psalms => 1..=150,
        Book::Proverbs => 1..=31,
        Book::Ecclesiastes => 1..=12,
        Book::SongOfSolomon => 1..=8,
        Book::Isaiah => 1..=66,
        Book::Jeremiah => 1..=52,
        Book::Lamentations => 1..=5,
        Book::Ezekiel => 1..=48,
        Book::Daniel => 1..=12,
        Book::Hosea => 1..=14,
        Book::Joel => 1..=3,
        Book::Amos => 1..=9,
        Book::Obadiah => 1..=1,
        Book::Jonah => 1..=4,
        Book::Micah => 1..=7,
        Book::Nahum => 1..=3,
        Book::Habakkuk => 1..=3,
        Book::Zephaniah => 1..=3,
        Book::Haggai => 1..=2,
        Book::Zechariah => 1..=14,
        Book::Malachi => 1..=4,
        Book::Matthew => 1..=28,
        Book::Mark => 1..=16,
        Book::Luke => 1..=24,
        Book::John => 1..=21,
        Book::Acts => 1..=28,
        Book::Romans => 1..=16,
        Book::Corinthians1 => 1..=16,
        Book::Corinthians2 => 1..=13,
        Book::Galatians => 1..=6,
        Book::Ephesians => 1..=6,
        Book::Philippians => 1..=4,
        Book::Colossians => 1..=4,
        Book::Thessalonians1 => 1..=5,
        Book::Thessalonians2 => 1..=3,
        Book::Timothy1 => 1..=6,
        Book::Timothy2 => 1..=4,
        Book::Titus => 1..=3,
        Book::Philemon => 1..=1,
        Book::Hebrews => 1..=13,
        Book::James => 1..=5,
        Book::Peter1 => 1..=5,
        Book::Peter2 => 1..=3,
        Book::John1 => 1..=5,
        Book::John2 => 1..=1,
        Book::John3 => 1..=1,
        Book::Jude => 1..=1,
        Book::Revelation => 1..=22,
    }
}

/// Knihy v Bibli.
///
/// ### Index
/// Číselná reprezentace tohoto enumu tvoří index do tabulky knih v databázi,
/// je velmi důležité, aby zůstala synchronizována s databází.
///
/// ### Reprezentace
/// Tento enum je reprezentován jako u8, tedy casty `Book::_ as u8` je bezpečné.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u8)]
pub enum Book {
    Genesis = 0,
    Exodus = 1,
    Leviticus = 2,
    Numbers = 3,
    Deuteronomy = 4,
    Joshua = 5,
    Judges = 6,
    Ruth = 7,
    Samuel1 = 8,
    Samuel2 = 9,
    Kings1 = 10,
    Kings2 = 11,
    Chronicles1 = 12,
    Chronicles2 = 13,
    Ezra = 14,
    Nehemiah = 15,
    Esther = 16,
    Job = 17,
    Psalms = 18,
    Proverbs = 19,
    Ecclesiastes = 20,
    SongOfSolomon = 21,
    Isaiah = 22,
    Jeremiah = 23,
    Lamentations = 24,
    Ezekiel = 25,
    Daniel = 26,
    Hosea = 27,
    Joel = 28,
    Amos = 29,
    Obadiah = 30,
    Jonah = 31,
    Micah = 32,
    Nahum = 33,
    Habakkuk = 34,
    Zephaniah = 35,
    Haggai = 36,
    Zechariah = 37,
    Malachi = 38,
    Matthew = 39,
    Mark = 40,
    Luke = 41,
    John = 42,
    Acts = 43,
    Romans = 44,
    Corinthians1 = 45,
    Corinthians2 = 46,
    Galatians = 47,
    Ephesians = 48,
    Philippians = 49,
    Colossians = 50,
    Thessalonians1 = 51,
    Thessalonians2 = 52,
    Timothy1 = 53,
    Timothy2 = 54,
    Titus = 55,
    Philemon = 56,
    Hebrews = 57,
    James = 58,
    Peter1 = 59,
    Peter2 = 60,
    John1 = 61,
    John2 = 62,
    John3 = 63,
    Jude = 64,
    Revelation = 65,
}

impl Book {
    /// Pokusí se zparsovat knihu z dodaného řetězce `input`. Pokud nelze zparsovat,
    /// vrátí `None`.
    ///
    /// ### Jak parsuje
    /// - Snaží se najít knihu, jejíž string-reprezentace má nejdelší shodný prefix s `input`
    /// - Pokud existuje jediná kniha se shodným prefixem, vrátí ji (kniha je jednoznačně určena)
    /// - Je case-insensitive
    ///
    /// ### Příklad
    /// ```rust
    /// # use ekkles_data::bible::indexing::Book;
    ///
    /// assert_eq!(Book::parse("Jan"), Some(Book::John));
    ///
    /// // "Ma" může znamenat "Matouš" nebo "Malachiáš", není to jednoznačné
    /// assert_eq!(Book::parse("Ma"), None);
    ///
    /// // Funguje case-insensitive
    /// assert_eq!(Book::parse("ža"), Some(Book::Psalms));
    /// ```
    pub fn parse(input: &str) -> Option<Book> {
        let input = input.to_lowercase();

        let mut common_chars: Vec<(Book, usize)> = BIBLE_BOOKS
            .iter()
            .map(|book| {
                let score = input
                    .chars()
                    .zip(book.to_string().to_lowercase().chars())
                    .take_while(|(input_char, book_char)| input_char == book_char)
                    .count();

                (*book, score)
            })
            .collect();

        common_chars.sort_unstable_by_key(|(_, score)| *score); // Nepotřebujeme zachovat pořadí položek se stejným klíčem, proto unstable (je rychlejší)
        common_chars.reverse(); // `sort()` vrací od nejmenšího, my chceme na začátku nejvyšší skóre

        // Pokud je první prvek větší než druhý, znamená, že vlastní jedinou nejdelší shodu
        // se vstupem, vrátíme tedy příslušnou knihu, jinak nelze unikátně identifikovat
        // knihu a vracíme None
        if common_chars[0].1 > common_chars[1].1 {
            Some(common_chars[0].0)
        } else {
            None
        }
    }
}

impl FromStr for Book {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        Book::parse(s).ok_or(anyhow!("{s} není biblická kniha"))
    }
}

impl TryFrom<u8> for Book {
    type Error = anyhow::Error;

    fn try_from(value: u8) -> std::result::Result<Self, Self::Error> {
        match value {
            0 => Ok(Book::Genesis),
            1 => Ok(Book::Exodus),
            2 => Ok(Book::Leviticus),
            3 => Ok(Book::Numbers),
            4 => Ok(Book::Deuteronomy),
            5 => Ok(Book::Joshua),
            6 => Ok(Book::Judges),
            7 => Ok(Book::Ruth),
            8 => Ok(Book::Samuel1),
            9 => Ok(Book::Samuel2),
            10 => Ok(Book::Kings1),
            11 => Ok(Book::Kings2),
            12 => Ok(Book::Chronicles1),
            13 => Ok(Book::Chronicles2),
            14 => Ok(Book::Ezra),
            15 => Ok(Book::Nehemiah),
            16 => Ok(Book::Esther),
            17 => Ok(Book::Job),
            18 => Ok(Book::Psalms),
            19 => Ok(Book::Proverbs),
            20 => Ok(Book::Ecclesiastes),
            21 => Ok(Book::SongOfSolomon),
            22 => Ok(Book::Isaiah),
            23 => Ok(Book::Jeremiah),
            24 => Ok(Book::Lamentations),
            25 => Ok(Book::Ezekiel),
            26 => Ok(Book::Daniel),
            27 => Ok(Book::Hosea),
            28 => Ok(Book::Joel),
            29 => Ok(Book::Amos),
            30 => Ok(Book::Obadiah),
            31 => Ok(Book::Jonah),
            32 => Ok(Book::Micah),
            33 => Ok(Book::Nahum),
            34 => Ok(Book::Habakkuk),
            35 => Ok(Book::Zephaniah),
            36 => Ok(Book::Haggai),
            37 => Ok(Book::Zechariah),
            38 => Ok(Book::Malachi),
            39 => Ok(Book::Matthew),
            40 => Ok(Book::Mark),
            41 => Ok(Book::Luke),
            42 => Ok(Book::John),
            43 => Ok(Book::Acts),
            44 => Ok(Book::Romans),
            45 => Ok(Book::Corinthians1),
            46 => Ok(Book::Corinthians2),
            47 => Ok(Book::Galatians),
            48 => Ok(Book::Ephesians),
            49 => Ok(Book::Philippians),
            50 => Ok(Book::Colossians),
            51 => Ok(Book::Thessalonians1),
            52 => Ok(Book::Thessalonians2),
            53 => Ok(Book::Timothy1),
            54 => Ok(Book::Timothy2),
            55 => Ok(Book::Titus),
            56 => Ok(Book::Philemon),
            57 => Ok(Book::Hebrews),
            58 => Ok(Book::James),
            59 => Ok(Book::Peter1),
            60 => Ok(Book::Peter2),
            61 => Ok(Book::John1),
            62 => Ok(Book::John2),
            63 => Ok(Book::John3),
            64 => Ok(Book::Jude),
            65 => Ok(Book::Revelation),
            _ => Err(anyhow!("Kniha s indexem vyšším než 65 neexistuje")),
        }
    }
}

impl Display for Book {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            Book::Genesis => "Genesis",
            Book::Exodus => "Exodus",
            Book::Leviticus => "Leviticus",
            Book::Numbers => "Numeri",
            Book::Deuteronomy => "Deuteronomium",
            Book::Joshua => "Jozue",
            Book::Judges => "Soudců",
            Book::Ruth => "Rút",
            Book::Samuel1 => "1. Samuelova",
            Book::Samuel2 => "2. Samuelova",
            Book::Kings1 => "1. Královská",
            Book::Kings2 => "2. Královská",
            Book::Chronicles1 => "1. Paralipomenon",
            Book::Chronicles2 => "2. Paralipomenon",
            Book::Ezra => "Ezdráš",
            Book::Nehemiah => "Nehemjáš",
            Book::Esther => "Ester",
            Book::Job => "Jób",
            Book::Psalms => "Žalmy",
            Book::Proverbs => "Přísloví",
            Book::Ecclesiastes => "Kazatel",
            Book::SongOfSolomon => "Píseň písní",
            Book::Isaiah => "Izajáš",
            Book::Jeremiah => "Jeremjáš",
            Book::Lamentations => "Pláč",
            Book::Ezekiel => "Ezechiel",
            Book::Daniel => "Daniel",
            Book::Hosea => "Ozeáš",
            Book::Joel => "Jóel",
            Book::Amos => "Ámos",
            Book::Obadiah => "Abdijáš",
            Book::Jonah => "Jonáš",
            Book::Micah => "Micheáš",
            Book::Nahum => "Nahum",
            Book::Habakkuk => "Abakuk",
            Book::Zephaniah => "Sofonjáš",
            Book::Haggai => "Ageus",
            Book::Zechariah => "Zacharjáš",
            Book::Malachi => "Malachiáš",
            Book::Matthew => "Matouš",
            Book::Mark => "Marek",
            Book::Luke => "Lukáš",
            Book::John => "Jan",
            Book::Acts => "Skutky",
            Book::Romans => "Římanům",
            Book::Corinthians1 => "1. Korintským",
            Book::Corinthians2 => "2. Korintským",
            Book::Galatians => "Galatským",
            Book::Ephesians => "Efezským",
            Book::Philippians => "Filipským",
            Book::Colossians => "Koloským",
            Book::Thessalonians1 => "1. Tesalonickým",
            Book::Thessalonians2 => "2. Tesalonickým",
            Book::Timothy1 => "1. Timoteovi",
            Book::Timothy2 => "2. Timoteovi",
            Book::Titus => "Titovi",
            Book::Philemon => "Filemonovi",
            Book::Hebrews => "Židům",
            Book::James => "Jakub",
            Book::Peter1 => "1. Petrova",
            Book::Peter2 => "2. Petrova",
            Book::John1 => "1. Janova",
            Book::John2 => "2. Janova",
            Book::John3 => "3. Janova",
            Book::Jude => "Juda",
            Book::Revelation => "Zjevení",
        };
        f.write_str(str)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verse_index_creation_test() {
        let valid = VerseIndex::try_new(Book::Romans, 3, 23);
        let invalid = VerseIndex::try_new(Book::Daniel, 16, 55);

        assert!(valid.is_some(), "Římanům 3:23 je validní odkaz");
        assert!(
            invalid.is_none(),
            "Daniel 16:55 neexistuje, nevalidní odkaz"
        );
    }
}
